# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2020-03-24 11:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='vd_club_card',
            fields=[
                ('card_number', models.IntegerField(max_length=10, primary_key=True, serialize=False, verbose_name='Номер карты')),
                ('state', models.CharField(choices=[('in_use', 'in_use'), ('not_in_use', 'not_in_use'), ('hidden', 'hidden')], max_length=100, verbose_name='Состояние')),
                ('price', models.IntegerField(max_length=10, verbose_name='Стоимость карты')),
                ('place', models.CharField(blank=True, default=' ', max_length=255, verbose_name='Местонахождение карты')),
            ],
            options={
                'verbose_name': 'Клубная карта',
                'ordering': ['card_number', 'state'],
                'verbose_name_plural': 'Клубные карты',
            },
        ),
        migrations.CreateModel(
            name='vd_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255, verbose_name='Мероприятие')),
                ('status', models.CharField(choices=[('Проведено', 'Проведено'), ('Дата утверждена', 'Дата утверждена'), ('В разработке', 'В разработке')], max_length=25, verbose_name='Статус')),
                ('many_days', models.CharField(choices=[('Нет', 'Нет'), ('Да', 'Да')], max_length=3, verbose_name='Многодневное')),
                ('data_plan', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Плановая дата')),
                ('data_begin', models.DateField(blank=True, verbose_name='Дата начала')),
                ('data_end', models.DateField(blank=True, verbose_name='Дата окончания')),
                ('event_type', models.CharField(choices=[('Авто', 'Авто'), ('Английский', 'Английский'), ('Вело', 'Вело'), ('Вечернее', 'Вечернее'), ('Водное', 'Водное'), ('ГК', 'ГК'), ('Игры', 'Игры'), ('Комбо', 'Комбо'), ('Коньки', 'Коньки'), ('Лыжи', 'Лыжи'), ('НГ', 'НГ'), ('Пешее', 'Пешее'), ('Психолог', 'Психолог'), ('Ролики', 'Ролики'), ('Хоккей', 'Хоккей'), ('ЧГК', 'ЧГК'), ('Эко', 'Эко')], max_length=25, verbose_name='Тип мероприятия')),
                ('vk_link', models.URLField(blank=True, max_length=100, verbose_name='Ссылка в vk')),
                ('level', models.CharField(choices=[('Новичок', 'Новичок'), ('Приключенческий', 'Приключенческий'), ('Профи', 'Профи'), (' - ', ' - ')], max_length=25, verbose_name='Уровень сложности')),
                ('country', models.CharField(blank=True, default=' ', max_length=50, verbose_name='Направление')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарии')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'ordering': ['-data_plan'],
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='vd_information_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inf_name', models.CharField(default=' ', max_length=254, verbose_name='Тип информации')),
                ('is_primary', models.BooleanField(default=True, verbose_name='Обязательное поле')),
            ],
            options={
                'verbose_name': 'Тип информации',
                'ordering': ['id'],
                'verbose_name_plural': 'Типы информации',
            },
        ),
        migrations.CreateModel(
            name='vd_organizer_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coeff', models.FloatField(verbose_name='Коэффициент')),
                ('event_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club.vd_event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Организатор мероприятия',
                'ordering': ['event_id', 'organizer_id'],
                'verbose_name_plural': 'Организаторы мероприятий',
            },
        ),
        migrations.CreateModel(
            name='vd_participent_event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club.vd_event', verbose_name='Мероприятие')),
            ],
            options={
                'verbose_name': 'Участник мероприятия',
                'ordering': ['event_id', 'participant_id'],
                'verbose_name_plural': 'Участники мероприятий',
            },
        ),
        migrations.CreateModel(
            name='vd_user_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inf_value', models.CharField(default=' ', max_length=254, verbose_name='Информация')),
                ('inf_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club.vd_information_type', verbose_name='Тип информации')),
            ],
            options={
                'verbose_name': 'Информация об участнике',
                'ordering': ['inf_type', 'user'],
                'verbose_name_plural': 'Информация об участниках',
            },
        ),
        migrations.CreateModel(
            name='vd_user_profile',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('last_name', models.CharField(db_index=True, default=' ', max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(default=' ', max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, default=' ', max_length=100, verbose_name='Отчество')),
                ('role', models.CharField(choices=[('Администратор', 'Администратор'), ('Организатор', 'Организатор'), ('Участник', 'Участник')], max_length=25, verbose_name='Роль')),
                ('comment', models.CharField(blank=True, default=' ', max_length=255, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Участник',
                'ordering': ['role'],
                'verbose_name_plural': 'Участники',
            },
        ),
        migrations.AddField(
            model_name='vd_user_information',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club.vd_user_profile', verbose_name='Ф.И.О. участника'),
        ),
        migrations.AddField(
            model_name='vd_participent_event',
            name='participant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club.vd_user_profile', verbose_name='Ф.И.О. участника'),
        ),
        migrations.AddField(
            model_name='vd_organizer_event',
            name='organizer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club.vd_user_profile', verbose_name='Ф.И.О. организатора'),
        ),
        migrations.AddField(
            model_name='vd_club_card',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.vd_user_profile', verbose_name='Ф.И.О.'),
        ),
    ]
